# Generated by Django 4.0.8 on 2022-12-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("title", models.TextField()),
                ("content", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["created_at"],
                "permissions": [("can_undelete", "Can undelete this object")],
                "abstract": False,
            },
        ),
    ]
